# Generated by Django 4.0.1 on 2023-04-09 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pantryitem',
            name='pantry_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppinglist.pantrycategory'),
        ),
    ]
