# Generated by Django 4.0.1 on 2023-04-10 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0002_pantryitem_pantry_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pantryitem',
            name='pantry_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shoppinglist.pantrycategory'),
        ),
    ]
