# Generated by Django 4.0.1 on 2022-01-28 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfriend',
            name='currently_friends',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userfriend',
            name='request_pending',
            field=models.BooleanField(default=False),
        ),
    ]
