# Generated by Django 4.0.1 on 2022-01-25 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='recipes.recipecategory'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_name',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='recipestep',
            name='instructions',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='recipestep',
            name='step_number',
            field=models.IntegerField(default=1),
        ),
    ]
