# Generated by Django 4.0.1 on 2022-01-25 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_recipe_category_recipe_recipe_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipecategory',
            name='category_name',
            field=models.CharField(default='other', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_category',
            field=models.ForeignKey(default='other', on_delete=django.db.models.deletion.SET_DEFAULT, to='recipes.recipecategory', to_field='category_name'),
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(default='N/A', max_length=100)),
                ('ingredient_quantity', models.CharField(default='N/A', max_length=50)),
                ('quantity_unit', models.CharField(default='N/A', max_length=50)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
    ]
