# Generated by Django 4.0.1 on 2022-01-26 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_image_alter_recipe_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_category',
            field=models.ForeignKey(default='other', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='recipes.recipecategory', to_field='category_name'),
        ),
    ]
