# Generated by Django 4.0.1 on 2022-01-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_recipe_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipestep',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
