# Generated by Django 4.0.1 on 2022-01-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_recipestep_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipestep',
            name='instructions',
            field=models.CharField(default='N/A', max_length=500),
        ),
    ]
