# Generated by Django 4.0.1 on 2022-01-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_alter_recipestep_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image_upload',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
