# Generated by Django 4.0.1 on 2022-01-28 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_alter_recipe_image_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image_upload',
            field=models.ImageField(blank=True, max_length=1500, null=True, upload_to='images/'),
        ),
    ]
