# Generated by Django 4.0.1 on 2022-01-28 23:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_alter_recipe_image_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image_upload',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
