# Generated by Django 4.0.1 on 2022-01-30 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_alter_recipe_image_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image_upload',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Image'),
        ),
    ]
