# Generated by Django 4.0.1 on 2022-01-30 00:47

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_alter_recipe_image_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image_upload',
            field=models.ImageField(blank=True, null=True, upload_to=recipes.models.upload_to, verbose_name='Image'),
        ),
    ]
