# Generated by Django 4.0.1 on 2022-01-30 05:06

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0022_remove_recipe_image_upload_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=recipes.models.upload_to, verbose_name='Image'),
        ),
    ]
