# Generated by Django 4.0.1 on 2023-02-26 20:36

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0023_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to=recipes.models.upload_to, verbose_name='Image'),
        ),
    ]
