# Generated by Django 4.0.1 on 2023-03-09 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0025_alter_ingredient_recipe_alter_recipestep_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_category',
        ),
        migrations.AddField(
            model_name='recipe',
            name='categories',
            field=models.ManyToManyField(null=True, related_name='recipes', to='recipes.RecipeCategory'),
        ),
    ]
