# Generated by Django 4.0.1 on 2023-03-30 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='meal_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
